<?php

return [
    'abdomen'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'back'=>'Orthopedic department', //قسم جراحة العظام
    'chest'=>'Pulmonology', //أمراض الرئة
    'ear'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'pelvis'=>'Orthopedic department',//قسم جراحة العظام
    'tooth'=>'Dentistry', //طب الأسنان
    'rectum'=>'Orthopedic department',//قسم جراحة العظام
    'skin'=>'Dermatology', //الجلدية
    'leg'=>'Orthopedic department',//قسم جراحة العظام
    'chronic-pain'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'fever'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'paresthesia'=>'Neurologists', //أطباء الأعصاب
    'light-headed'=>'Ophthalmology', //طب العيون
    'dizzy-about-to-black-out'=>'Neurologists', //أطباء الأعصاب
    'dizzy-with-the-room-spinning-around-me'=>'Neurologists', //أطباء الأعصاب
    'my-mouth-is-dry'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'flu'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'vomit'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'short-of-breath'=>'Pulmonology',//أمراض الرئة
    'sleepy'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'sweaty'=>'Dermatology', //الجلدية
    'thirsty'=>'Pulmonology',//أمراض الرئة
    'tired'=>'Pulmonology',//أمراض الرئة
    'weak'=>'Pulmonology',//أمراض الرئة
    'breathe'=>'Pulmonology',//أمراض الرئة
    'losing-hearing'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'sounds-are-too-loud'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'ringing-or-hissing-in-my-ears'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'move-one-side'=>'Orthopedic department',//قسم جراحة العظام
    'pass-a-bowel-action-normally'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'urine'=>'Urology', //جراحة المسالك البولية
    'remember'=>'Neurologists', //أطباء الأعصاب
    'blindness'=>'Ophthalmology', //طب العيون
    'blurred-vision'=>'Ophthalmology', //طب العيون
    'double-vision'=>'Ophthalmology', //طب العيون
    'sleep'=>'Neurologists', //أطباء الأعصاب
    'smell'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'speak'=>'Neurologists', //أطباء الأعصاب
    'stop-passing-watery-bowel-actions'=>'Dermatology', //الجلدية
    'stop-scratching'=>'Dermatology', //الجلدية
    'sweating'=>'Dermatology', //الجلدية
    'swallow'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'taste-properly'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'walk'=>'Neurologists', //أطباء الأعصاب
    'write'=>'Neurologists', //أطباء الأعصاب
    'anorexia'=>'Eating disorder', //اضطرابات الطعام
    'weight-loss'=>'Eating disorder', //اضطرابات الطعام
    'convulsions'=>'Neurologists', //أطباء الأعصاب
    'deformity'=>'Dermatology', //الجلدية
    'dizziness'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'hypothermia'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'muscle-weakness'=>'natural therapy', //العلاج الطبيعي
    'sweats'=>'Dermatology', //الجلدية
    'swelling'=>'Dermatology', //الجلدية
    'arrhythmia'=>'Cardiovascular Medicine', //طب القلب والأوعية الدموية
    'bradycardia'=>'Cardiovascular Medicine', //طب القلب والأوعية الدموية
    'chest'=>'Pulmonology',//أمراض الرئة
    'claudication'=>'Orthopedic department', //قسم جراحة العظام
    'tachycardia'=>'Cardiovascular Medicine', //طب القلب والأوعية الدموية
    'dry'=>'Gastroenterology',// أمراض الجهاز الهضمي
    'halitosis'=>'Dentistry', //طب الأسنان
    'hearing-loss'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'nasal-discharge'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'sore-throat'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'toothache'=>'Dentistry', //طب الأسنان
    'tinnitus'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'abdominal'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'bloating'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'hematemesis'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'constipation'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'diarrhea'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'dysphagia'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'dyspepsia'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'fecal-incontinence'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'flatulence'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'heartburn'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'nausea'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'odynophagia'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'pyrosis'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'rectal-tenesmus'=>'Otorhinolaryngology', //طب الأنف والأذن والحنجرة
    'steatorrhea'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'vomiting'=>'Gastroenterology', // أمراض الجهاز الهضمي
    'alopecia'=>'Dermatology', //الجلدية
    'hirsutism'=>'Dermatology', //الجلدية
    'hypertrichosis'=>'Dermatology', //الجلدية
    'abrasion'=>'Dermatology', //الجلدية
    'petechia'=>'Dermatology', //الجلدية
    'laceration'=>'natural therapy', //العلاج الطبيعي
    
];